/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrador' at '20/12/16 11:33' with Gradle 2.6
 *
 * @author Administrador, @date 20/12/16 11:33
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
